service: sls-boilerplate

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: ap-northeast-2

package:
    include:
    exclude:
        - src/**

functions:
    hello:
        handler: dist/handler.hello
        memorySize: 128
        events:
            - http:
                path: hello
                method: get
                cors: true
    helloWithInput:
        handler: dist/handler.hello
        memorySize: 128
        events:
            - http:
                path: hello/{pathnameInput}
                method: post
                cors: true
